var quotes = [
  "Von Nichts zu noch weniger",
  "Wenn Du die Wahl hast, tue beides",
  "Gehe bis ins Extrem und zurück in einen komfortablen Bereich",
  "Linker Kanal, rechter Kanal, mittlerer Kanal",
  "Würde es irgendjemand haben wollen?",
  "Setz Dir Deine Kopfhörer auf",
  "Brücken 1.bauen 2.niederbrennen",
  "Räum auf",
  "Stummschalten und weiter machen",
  "Suche das peinlichste Detail und rücke es in den Vordergrund",
  "Benutze eine unakzepptable Farbe",
  "Lass Dir den Nacken massieren",
  "Zurückverfolge Deine Schritte",
  "Was würdest Du eigentlich nicht tun?",
  "Ins Unmögliche",
  "Mache eine vollständige Liste aller Dinge, die Du tun könntest und mache das letzte auf der Liste",
  "Mut!",
  "Kurzschluss (Falls Erbsen deine Potenz steigern, schaufel welche in deine Hosen",
  "Mache eine Leerstelle nützlich, indem Du sie in einen exklusiven Rahmen stellst",
  "Gehe langsam einmal um das Äußere",
  "Zerstöre 1.nichts 2.die wichtigste Sache",
  "(Organisches) Maschinengeräusch",
  "Wenn man erstmal anfängt zu suchen, findet man auch etwas",
  "Sei schmutzig",
  "Erinnere Dich an die ruhigen Abende",
  'Lass Dir von "unqualifizierten" Freunden helfen',
  "Hab keine Angst Deine Talente zu zeigen",
  "Mach den Abwasch",
  "Schmücke und dekoriere",
  "Stell es auf den Kopf",
  "Benutze weniger Noten",
  "Gib Deinem schlimmsten Drang nach",
  "Gibt es einzelne Abschnitte? Dann denk auch an die Übergänge",
  "Nimm Deine bisherige Aufnahme nochmal mit einem Mikrofon auf",
  "[Leere Karte]",
  "Frag Deinen Körper",
  "Benutz eine alte Idee",
  "Stell Dir das Ganze als einzelne voneinander unabhängige Teile vor",
  "Lösche Elemente in der Reihenfolge ihrer Unwichtigkeit",
  "Verwandle ein melodisches Element in ein rhythmisches Element",
  "Entdecke Deine typische Vorgehensweise und wirf sie über Bord",
  "Welche Fehler hast Du letztes mal gemacht?",
  "Hör der leisen Stimme zu",
  "Gestatte eine Erleichterung (Eine Erleichterung ist die Verbannung einer scharfen Kritik)",
  "Vertausche die Rollen der Instrumente",
  "Kleinster gemeinsamer Nenner",
  "Zerstöre nicht die Stille",
  "Ändere nichts und mach weiter mit makelloser Beständigkeit",
  "Fülle jeden Takt mit irgendetwas",
  "Wiederholung ist eine Art der Veränderung",
  "Immer erste Schritte",
  "Zusatz",
  "Brauchen wir Lücken?",
  "Wasser",
  "Sei des öfteren mal weniger kritisch",
  "Disziplinierter Genuss",
  "Gruppiere einige Elemente und wende Effekte auf die ganze Gruppe an",
  "Ist die Intonation korrekt?",
  "Wie ist die Realität der Situation?",
  "Einfache Subtraktion",
  "Verdrehe die stützende Säule",
  "Vermeide absichtlich Änderung",
  "In totaler Dunkelheit, in einem riesigen Raum und ganz leise",
  "Erwäge andere Überblendungen",
  "Probiere andere Quellen aus 1.vielversprechende 2.weniger vielversprechende",
  "Dem Unbedeutenden entgegen!",
  "Denk an Radio",
  "Mache etwas Perfektes menschlicher",
  "Idiotische Fröhlichkeit",
  "Wie hättest Du es sonst gemacht?",
  "Mach eine Pause",
  "Lobe Dich stets für mehr Persönlichkeit",
  "Führe eine plötzliche unvorhersehbare Aktion aus und baue sie ein",
  "Entferne Zweideutigkeiten und verwandle sie in Eindeutigkeiten",
  "Müssten die Wörter eventuell geändert werden?",
  "Atme tiefer ein",
  "Keine Mauer bauen, aber einen einzelnen Stein entwerfen",
  "Glaube jetzt an Dich",
  "Das Unbeständigkeitsprinzip",
  "Zu welchen Teilen gehören die Elemente? Stell Dir vor, wie sich eine Raupe bewegt",
  "Rückwärts",
  "Beanspruche eine Sache nicht mehr als eine andere",
  "Benutze Filter",
  "Dominosteine",
  "Du musst Dich nicht schämen, wenn Du Deine eigenen Ideen verwendest",
  "Ein sehr kleines Detail, dessen Mitte",
  'Definiere einen Bereich als "sicher" und benutze ihn als Anker',
  "Eine Reihe hat zwei Enden",
  "Sei extravagant",
  "Neubeurteilung (ein warmes Gefühl)",
  "Du bist ein Ingenieur",
  "Betone Wiederholungen",
  "Ist es fertig?",
  "Mechanisiere etwas Eigenwilliges",
  "Du kannst nur einen Punkt nach dem anderen machen",
  "Zeit zum Verzerren",
  "Kinder 1.singen 2.sprechen",
  "Unendlich kleine Abstufungen",
  "Gruppenanalyse",
  "Betone die Fehler",
  "Spektralanalyse",
  "Arbeite in verschiedenen Geschwindigkeiten",
  " "
];
